server:
    port: 8080
spring:
    datasource:
        url: jdbc:postgresql://localhost:1234/db_docker
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob.non-contextual-creation: true
        properties:
            hibernate:
                show_sql: true

